#version 460
#define GLSL

#define COMPUTE_SHADER

#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (binding = 0, rgba8) uniform image2D resultImage;

void main()
{
    float color = length(vec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)) / 4000.0;

    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), vec4(color.rrr, 1.0));
}
